// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Shipment.Infrastructure.Persistence.EFCore;

#nullable disable

namespace TruckDelivery.Shipment.Infrastructure.Persistence.EFCore.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260430000001_AddCoordinatesToShipment")]
    partial class AddCoordinatesToShipment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
