// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckDelivery.Shipment.Infrastructure.Persistence.EFCore;

#nullable disable

namespace TruckDelivery.Shipment.Infrastructure.Persistence.EFCore.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260428073742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipment")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TruckDelivery.Shared.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("ProcessedAt", "RetryCount");

                    b.ToTable("outbox_messages", "shipment");
                });

            modelBuilder.Entity("TruckDelivery.Shipment.Domain.Aggregates.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assigned_driver_id");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("delivery_city");

                    b.Property<string>("DeliveryProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("delivery_province");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<string>("PickupCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pickup_city");

                    b.Property<string>("PickupProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pickup_province");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalVolumeCbm")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_volume_cbm");

                    b.Property<decimal>("TotalWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_weight_kg");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("shipments", "shipment");
                });

            modelBuilder.Entity("TruckDelivery.Shipment.Domain.Aggregates.Shipment", b =>
                {
                    b.OwnsOne("TruckDelivery.Shipment.Domain.ValueObjects.RouteInfo", "Route", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("char(36)");

                            b1.Property<double>("DistanceMeters")
                                .HasColumnType("double")
                                .HasColumnName("route_distance_m");

                            b1.Property<double>("DurationSeconds")
                                .HasColumnType("double")
                                .HasColumnName("route_duration_s");

                            b1.Property<string>("EncodedPolyline")
                                .HasMaxLength(5000)
                                .HasColumnType("varchar(5000)")
                                .HasColumnName("route_polyline");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments", "shipment");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
