// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Payment.Infrastructure.Persistence.EFCore;

#nullable disable

namespace TruckDelivery.Payment.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260503000000_AddDriverIdToPayments")]
    partial class AddDriverIdToPayments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
