// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Order.Infrastructure.Persistence;

#nullable disable

namespace TruckDelivery.Order.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260430000000_AddShipmentIdToOrder")]
    partial class AddShipmentIdToOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
