// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Identity.Infrastructure.Persistence;

#nullable disable

namespace TruckDelivery.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260501000000_AddPhoneAndDateOfBirth")]
    partial class AddPhoneAndDateOfBirth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
