// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Notification.Infrastructure.Persistence.EFCore;

#nullable disable

namespace TruckDelivery.Notification.Infrastructure.Persistence.EFCore.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260430000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
