// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TruckDelivery.Driver.Infrastructure.Persistence;

#nullable disable

namespace TruckDelivery.Driver.Infrastructure.Migrations
{
    [DbContext(typeof(DriverDbContext))]
    [Migration("20260501000000_AddBreakdownAndSwapRecords")]
    partial class AddBreakdownAndSwapRecords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
